# Generated by Django 5.2 on 2026-06-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdata',
            name='fiscal_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
